sudo: required

language: node_js
node_js:
  - "8"

services:
  - docker

before_install:
  #- export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - npm install
  - npm run build
  - npm run test

after_success:
  - docker build -t denysvuika/ng-docker .
